[package]
name = "ecoinvent-example"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
lca-core = { path = "../lca-core" }
lca-rs = { path = "../lca-rs" }
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.11.8"
log = "0.4.27"
