[package]
name = "lca-database"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["from", "error", "display"] }
serde = { version = "1.0", features = ["derive"] }
surrealdb = "2.3.3"
uuid = { version = "1.17", features = ["serde", "v7"] }
ecospold-parser = { path = "../ecospold-parser" }
tokio = { version = "1.45.1", features = ["full"] }
chrono = { version = "0.4.41", features = ["serde"] }
indicatif = { version = "0.17.11", features = ["tokio"] }
serde_json = { version = "1.0.140", features = ["preserve_order"] }
itertools = "0.14.0"
geo = { version = "0.30.0", features = ["use-serde"] }
